### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by mikebutts** [kodaxx/codecademy_react#1]
https://github.com/kodaxx/codecademy_react/blob/0344df814bb9ca86a79b2f0361608844153c45ee/jammming/src/util/Spotify.js#L3

Try to get this deployed! https://medium.freecodecamp.org/surge-vs-github-pages-deploying-a-create-react-app-project-c0ecbf317089

**Comment by kodaxx** [comment]
This has already been deployed kodaxxjam.surge.sh - redirectURI was changed after pushing
