### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [kodaxx/codecademy_react#6]
Meets Expectations

Good job on this project! I left some issues with alternatives to your current code. The way it works now is fine this just shows you otherways to tackle the code. Also try to get this deployed on github or surge. Good job! Try to add the request feature, I am sure you can do it.

**Comment by kodaxx** [comment]
Thanks for the feedback - the alternatives helped quite a bit. My project was already deployed before hand at kodaxxjam.surge.sh but I will add the request feature. Thanks again
